import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import React from 'react';

const inter = localFont({
  src: '../fonts/Inter-VariableFont_opsz,wght.ttf',
});

export const metadata: Metadata = {
  title: 'ticket-app',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>
  );
}
